study_prefix = "covid"

[sql_config]
file_names = [
    "site_define.sql",
    "covid_define_symptom.sql",
    "covid_define.sql",
    "count_covid_study_period.sql",
    "count_covid_dx.sql",
    "count_covid_pcr.sql",
    "count_covid_symptom.sql",
    "count_covid_prevalence_ed.sql",
]


[export_config]
export_list = [
    "covid__count_prevalence_ed_month",
    "covid__count_dx_week",
    "covid__count_pcr_week",
    "covid__count_prevalence_ed_month",
    "covid__count_study_period",
    "covid__count_symptom_week",
    "covid__meta_date",
]
