name: CI
on: [push]
jobs:
  unittest:
    name: unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Get library from main
        run: pip install git+https://github.com/smart-on-fhir/cumulus-library.git
      
      - name: Install linters
        run: |
          python -m pip install --upgrade pip
          pip install ".[dev]"
      - name: Run sqlfluff on jinja templates
        run: |
          sqlfluff lint
            - name: Run ruff
        if: success() || failure() # still run ruff if above checks fails
        run: |
          ruff check
          ruff format --check
