name: CI
on: [push]
jobs:
  unittest:
    name: unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[tests]

      - name: Test with pytest
        run: python -m pytest

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install linters
        run: |
          python -m pip install --upgrade pip
          pip install ".[dev]"
      - name: Run sqlfluff on jinja templates
        run: |
          sqlfluff lint
      - name: Run ruff
        if: success() || failure() # still run ruff if above checks fails
        run: |
          ruff check
          ruff format --check
